### ISSUE TITLE
Get smart contract address from URL query parameter

### ISSUE THREAD

**Issue by htadashi** [tintinweb/smart-contract-storage-viewer#2]
Hi @tintinweb, thanks again for building another useful tool for Ethereum developers!
Would it be possible to modify the page to get the smart contract address from a URL query parameter?

That would make the tool easy interoperable with other tools such as https://github.com/apoorvlathey/eth-explorers-extension :)

**Comment by tintinweb** [comment]
implemented. just provide the target address in the URI.search part, like:

https://tintinweb.github.io/smart-contract-storage-viewer?0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

cheers 🙌
